# Generated by Django 5.1 on 2024-09-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
